CREATE TABLE PRO_PROCESO (
    PRO_ID INT PRIMARY KEY,
    PRO_NOMBRE VARCHAR(255),
    PRO_PREFIJO VARCHAR(10) 
);

CREATE TABLE TIP_TIPO_DOC (
    TIP_ID INT PRIMARY KEY,
    TIP_NOMBRE VARCHAR(255),
    TIP_PREFIJO VARCHAR(10) 
);

CREATE TABLE DOC_DOCUMENTO (
    DOC_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIP_PREFIJO VARCHAR(10),
    PRO_PREFIJO VARCHAR(10),
    DOCUMENTO_CODIGO VARCHAR(255),
    FOREIGN KEY (TIP_PREFIJO) REFERENCES TIP_TIPO_DOC(TIP_PREFIJO),
    FOREIGN KEY (PRO_PREFIJO) REFERENCES PRO_PROCESO(PRO_PREFIJO)
);